export interface TechStackItem {
  iconName: string;
  name: string;
  short: string;
  type: string;
  logoPath: string;
}

export const TechStack: TechStackItem[] = [
  // 🧠 Languages
  {
    iconName: "typescript",
    name: "TypeScript",
    short: "ts",
    type: "language",
    logoPath: "/svg/TypeScript.svg",
  },
  {
    iconName: "javascript",
    name: "JavaScript",
    short: "js",
    type: "language",
    logoPath: "/svg/JavaScript.svg",
  },
  {
    iconName: "python",
    name: "Python",
    short: "py",
    type: "language",
    logoPath: "/svg/Python.svg",
  },
  {
    iconName: "go",
    name: "Go",
    short: "go",
    type: "language",
    logoPath: "/svg/Go.svg",
  },
  {
    iconName: "rust",
    name: "Rust",
    short: "rs",
    type: "language",
    logoPath: "/svg/Rust.svg",
  },
  {
    iconName: "java",
    name: "Java",
    short: "java",
    type: "language",
    logoPath: "/svg/Java.svg",
  },
  {
    iconName: "csharp",
    name: "C#",
    short: "cs",
    type: "language",
    logoPath: "/svg/CSharp.svg",
  },
  {
    iconName: "cplusplus",
    name: "C++",
    short: "cpp",
    type: "language",
    logoPath: "/svg/CPlusPlus.svg",
  },
  {
    iconName: "c",
    name: "C",
    short: "c",
    type: "language",
    logoPath: "/svg/C.svg",
  },
  {
    iconName: "php",
    name: "PHP",
    short: "php",
    type: "language",
    logoPath: "/svg/PHP.svg",
  },
  {
    iconName: "ruby",
    name: "Ruby",
    short: "rb",
    type: "language",
    logoPath: "/svg/Ruby.svg",
  },
  {
    iconName: "kotlin",
    name: "Kotlin",
    short: "kt",
    type: "language",
    logoPath: "/svg/Kotlin.svg",
  },
  {
    iconName: "swift",
    name: "Swift",
    short: "swift",
    type: "language",
    logoPath: "/svg/Swift.svg",
  },
  {
    iconName: "dart",
    name: "Dart",
    short: "dart",
    type: "language",
    logoPath: "/svg/Dart.svg",
  },
  {
    iconName: "scala",
    name: "Scala",
    short: "scala",
    type: "language",
    logoPath: "/svg/Scala.svg",
  },
  {
    iconName: "elixir",
    name: "Elixir",
    short: "ex",
    type: "language",
    logoPath: "/svg/Elixir.svg",
  },
  {
    iconName: "haskell",
    name: "Haskell",
    short: "hs",
    type: "language",
    logoPath: "/svg/Haskell.svg",
  },
  {
    iconName: "lua",
    name: "Lua",
    short: "lua",
    type: "language",
    logoPath: "/svg/Lua.svg",
  },
  {
    iconName: "r",
    name: "R",
    short: "r",
    type: "language",
    logoPath: "/svg/R-.svg",
  },
  {
    iconName: "julia",
    name: "Julia",
    short: "jl",
    type: "language",
    logoPath: "/svg/Julia.svg",
  },
  {
    iconName: "clojure",
    name: "Clojure",
    short: "clj",
    type: "language",
    logoPath: "/svg/Clojure.svg",
  },
  {
    iconName: "clojurescript",
    name: "ClojureScript",
    short: "cljs",
    type: "language",
    logoPath: "/svg/ClojureScript.svg",
  },
  {
    iconName: "erlang",
    name: "Erlang",
    short: "erl",
    type: "language",
    logoPath: "/svg/Erlang.svg",
  },
  {
    iconName: "groovy",
    name: "Apache Groovy",
    short: "groovy",
    type: "language",
    logoPath: "/svg/Apache-Groovy.svg",
  },
  {
    iconName: "perl",
    name: "Perl",
    short: "pl",
    type: "language",
    logoPath: "/svg/Perl.svg",
  },
  {
    iconName: "bash",
    name: "Bash",
    short: "bash",
    type: "language",
    logoPath: "/svg/Bash.svg",
  },
  {
    iconName: "powershell",
    name: "PowerShell",
    short: "ps1",
    type: "language",
    logoPath: "/svg/Powershell.svg",
  },
  {
    iconName: "coffeescript",
    name: "CoffeeScript",
    short: "coffee",
    type: "language",
    logoPath: "/svg/CoffeeScript.svg",
  },
  {
    iconName: "crystal",
    name: "Crystal",
    short: "cr",
    type: "language",
    logoPath: "/svg/Crystal.svg",
  },
  {
    iconName: "fsharp",
    name: "F#",
    short: "fs",
    type: "language",
    logoPath: "/svg/FSharp-(F#).svg",
  },
  {
    iconName: "fortran",
    name: "Fortran",
    short: "f90",
    type: "language",
    logoPath: "/svg/Fortran.svg",
  },
  {
    iconName: "objectivec",
    name: "Objective-C",
    short: "objc",
    type: "language",
    logoPath: "/svg/Objective-C.svg",
  },
  {
    iconName: "ocaml",
    name: "OCaml",
    short: "ml",
    type: "language",
    logoPath: "/svg/OCaml.svg",
  },
  {
    iconName: "elm",
    name: "Elm",
    short: "elm",
    type: "language",
    logoPath: "/svg/Elm.svg",
  },
  {
    iconName: "nim",
    name: "Nim",
    short: "nim",
    type: "language",
    logoPath: "/svg/Nim.svg",
  },
  {
    iconName: "solidity",
    name: "Solidity",
    short: "sol",
    type: "language",
    logoPath: "/svg/Solidity.svg",
  },
  {
    iconName: "vyper",
    name: "Vyper",
    short: "vy",
    type: "language",
    logoPath: "/svg/Vyper.svg",
  },
  {
    iconName: "purescript",
    name: "PureScript",
    short: "purs",
    type: "language",
    logoPath: "/svg/PureScript.svg",
  },
  {
    iconName: "ballerina",
    name: "Ballerina",
    short: "bal",
    type: "language",
    logoPath: "/svg/Ballerina.svg",
  },
  {
    iconName: "haxe",
    name: "Haxe",
    short: "hx",
    type: "language",
    logoPath: "/svg/Haxe.svg",
  },
  {
    iconName: "vala",
    name: "Vala",
    short: "vala",
    type: "language",
    logoPath: "/svg/Vala.svg",
  },
  {
    iconName: "zig",
    name: "Zig",
    short: "zig",
    type: "language",
    logoPath: "/svg/Zig.svg",
  },
  {
    iconName: "jule",
    name: "Jule",
    short: "jule",
    type: "language",
    logoPath: "/svg/Jule.svg",
  },
  {
    iconName: "apl",
    name: "APL",
    short: "apl",
    type: "language",
    logoPath: "/svg/APL.svg",
  },
  {
    iconName: "awk",
    name: "AWK",
    short: "awk",
    type: "language",
    logoPath: "/svg/Awk.svg",
  },
  {
    iconName: "html5",
    name: "HTML5",
    short: "html",
    type: "language",
    logoPath: "/svg/HTML5.svg",
  },
  {
    iconName: "css3",
    name: "CSS3",
    short: "css",
    type: "language",
    logoPath: "/svg/CSS3.svg",
  },

  // ⚙️ Frameworks
  {
    iconName: "nextjs",
    name: "Next.js",
    short: "next",
    type: "framework",
    logoPath: "/svg/Next.js.svg",
  },
  {
    iconName: "expressjs",
    name: "Express.js",
    short: "express",
    type: "framework",
    logoPath: "/svg/Express.svg",
  },
  {
    iconName: "nestjs",
    name: "NestJS",
    short: "nest",
    type: "framework",
    logoPath: "/svg/Nest.js.svg",
  },
  {
    iconName: "django",
    name: "Django",
    short: "django",
    type: "framework",
    logoPath: "/svg/Django.svg",
  },
  {
    iconName: "fastapi",
    name: "FastAPI",
    short: "fastapi",
    type: "framework",
    logoPath: "/svg/FastAPI.svg",
  },
  {
    iconName: "flask",
    name: "Flask",
    short: "flask",
    type: "framework",
    logoPath: "/svg/Flask.svg",
  },
  {
    iconName: "spring",
    name: "Spring",
    short: "spring",
    type: "framework",
    logoPath: "/svg/Spring.svg",
  },
  {
    iconName: "laravel",
    name: "Laravel",
    short: "laravel",
    type: "framework",
    logoPath: "/svg/Laravel.svg",
  },
  {
    iconName: "rails",
    name: "Ruby on Rails",
    short: "rails",
    type: "framework",
    logoPath: "/svg/Ruby-on-Rails.svg",
  },
  {
    iconName: "astro",
    name: "Astro",
    short: "astro",
    type: "framework",
    logoPath: "/svg/Astro.svg",
  },
  {
    iconName: "gatsby",
    name: "Gatsby",
    short: "gatsby",
    type: "framework",
    logoPath: "/svg/Gatsby.svg",
  },
  {
    iconName: "nuxt",
    name: "Nuxt.js",
    short: "nuxt",
    type: "framework",
    logoPath: "/svg/Nuxt-JS.svg",
  },
  {
    iconName: "adonisjs",
    name: "AdonisJS",
    short: "adonis",
    type: "framework",
    logoPath: "/svg/AdonisJS.svg",
  },
  {
    iconName: "cakephp",
    name: "CakePHP",
    short: "cake",
    type: "framework",
    logoPath: "/svg/CakePHP.svg",
  },
  {
    iconName: "codeigniter",
    name: "CodeIgniter",
    short: "ci",
    type: "framework",
    logoPath: "/svg/CodeIgniter.svg",
  },
  {
    iconName: "symfony",
    name: "Symfony",
    short: "symfony",
    type: "framework",
    logoPath: "/svg/Symfony.svg",
  },
  {
    iconName: "yii",
    name: "Yii Framework",
    short: "yii",
    type: "framework",
    logoPath: "/svg/Yii-Framework.svg",
  },
  {
    iconName: "phalcon",
    name: "Phalcon",
    short: "phalcon",
    type: "framework",
    logoPath: "/svg/Phalcon.svg",
  },
  {
    iconName: "lumen",
    name: "Lumen",
    short: "lumen",
    type: "framework",
    logoPath: "/svg/Lumen.svg",
  },
  {
    iconName: "phoenix",
    name: "Phoenix Framework",
    short: "phoenix",
    type: "framework",
    logoPath: "/svg/Phoenix-Framework.svg",
  },
  {
    iconName: "quarkus",
    name: "Quarkus",
    short: "quarkus",
    type: "framework",
    logoPath: "/svg/Quarkus.svg",
  },
  {
    iconName: "grails",
    name: "Grails",
    short: "grails",
    type: "framework",
    logoPath: "/svg/Grails.svg",
  },
  {
    iconName: "ktor",
    name: "Ktor",
    short: "ktor",
    type: "framework",
    logoPath: "/svg/Ktor.svg",
  },
  {
    iconName: "vertx",
    name: "Eclipse Vert.x",
    short: "vertx",
    type: "framework",
    logoPath: "/svg/Eclipse-Vert.x.svg",
  },
  {
    iconName: "akka",
    name: "Akka",
    short: "akka",
    type: "framework",
    logoPath: "/svg/Akka.svg",
  },
  {
    iconName: "dropwizard",
    name: "Dropwizard",
    short: "dropwizard",
    type: "framework",
    logoPath: "/svg/Dropwizard.svg",
  },
  {
    iconName: "fastify",
    name: "Fastify",
    short: "fastify",
    type: "framework",
    logoPath: "/svg/Fastify.svg",
  },
  {
    iconName: "feathers",
    name: "Feathers",
    short: "feathers",
    type: "framework",
    logoPath: "/svg/Feathers.svg",
  },
  {
    iconName: "moleculer",
    name: "Moleculer",
    short: "moleculer",
    type: "framework",
    logoPath: "/svg/Moleculer.svg",
  },
  {
    iconName: "qt",
    name: "Qt Framework",
    short: "qt",
    type: "framework",
    logoPath: "/svg/Qt-Framework.svg",
  },
  {
    iconName: "dotnet",
    name: ".NET",
    short: "dotnet",
    type: "framework",
    logoPath: "/svg/.NET.svg",
  },
  {
    iconName: "dotnetcore",
    name: ".NET Core",
    short: "dotnetcore",
    type: "framework",
    logoPath: "/svg/.NET-core.svg",
  },
  {
    iconName: "djangorest",
    name: "Django REST",
    short: "drf",
    type: "framework",
    logoPath: "/svg/Django-REST.svg",
  },

  // 🎨 Frontend
  {
    iconName: "react",
    name: "React",
    short: "react",
    type: "frontend",
    logoPath: "/svg/React.svg",
  },
  {
    iconName: "vuejs",
    name: "Vue.js",
    short: "vue",
    type: "frontend",
    logoPath: "/svg/Vue.js.svg",
  },
  {
    iconName: "svelte",
    name: "Svelte",
    short: "svelte",
    type: "frontend",
    logoPath: "/svg/Svelte.svg",
  },
  {
    iconName: "angular",
    name: "Angular",
    short: "ng",
    type: "frontend",
    logoPath: "/svg/Angular.svg",
  },
  {
    iconName: "angularjs",
    name: "AngularJS",
    short: "angularjs",
    type: "frontend",
    logoPath: "/svg/AngularJS.svg",
  },
  {
    iconName: "tailwindcss",
    name: "Tailwind CSS",
    short: "tw",
    type: "frontend",
    logoPath: "/svg/Tailwind-CSS.svg",
  },
  {
    iconName: "redux",
    name: "Redux",
    short: "redux",
    type: "frontend",
    logoPath: "/svg/Redux.svg",
  },
  {
    iconName: "bootstrap",
    name: "Bootstrap",
    short: "bootstrap",
    type: "frontend",
    logoPath: "/svg/Bootstrap.svg",
  },
  {
    iconName: "materialui",
    name: "Material UI",
    short: "mui",
    type: "frontend",
    logoPath: "/svg/Material-UI.svg",
  },
  {
    iconName: "sass",
    name: "Sass",
    short: "sass",
    type: "frontend",
    logoPath: "/svg/Sass.svg",
  },
  {
    iconName: "less",
    name: "Less.js",
    short: "less",
    type: "frontend",
    logoPath: "/svg/Less.js.svg",
  },
  {
    iconName: "stylus",
    name: "Stylus",
    short: "stylus",
    type: "frontend",
    logoPath: "/svg/Stylus.svg",
  },
  {
    iconName: "threejs",
    name: "Three.js",
    short: "three",
    type: "frontend",
    logoPath: "/svg/Three.js.svg",
  },
  {
    iconName: "solidjs",
    name: "Solid.js",
    short: "solid",
    type: "frontend",
    logoPath: "/svg/Solid.js.svg",
  },
  {
    iconName: "jquery",
    name: "jQuery",
    short: "jquery",
    type: "frontend",
    logoPath: "/svg/jQuery.svg",
  },
  {
    iconName: "ember",
    name: "Ember.js",
    short: "ember",
    type: "frontend",
    logoPath: "/svg/Ember.js.svg",
  },
  {
    iconName: "backbone",
    name: "Backbone.js",
    short: "backbone",
    type: "frontend",
    logoPath: "/svg/Backbone.js.svg",
  },
  {
    iconName: "d3",
    name: "D3.js",
    short: "d3",
    type: "frontend",
    logoPath: "/svg/D3.js.svg",
  },
  {
    iconName: "alpinejs",
    name: "Alpine.js",
    short: "alpine",
    type: "frontend",
    logoPath: "/svg/Alpine.js.svg",
  },
  {
    iconName: "knockout",
    name: "Knockout",
    short: "knockout",
    type: "frontend",
    logoPath: "/svg/Knockout.svg",
  },
  {
    iconName: "meteorjs",
    name: "Meteor.js",
    short: "meteor",
    type: "frontend",
    logoPath: "/svg/Meteor.js.svg",
  },
  {
    iconName: "mobx",
    name: "MobX",
    short: "mobx",
    type: "frontend",
    logoPath: "/svg/MobX.svg",
  },
  {
    iconName: "antdesign",
    name: "Ant Design",
    short: "antd",
    type: "frontend",
    logoPath: "/svg/Ant-Design.svg",
  },
  {
    iconName: "bulma",
    name: "Bulma",
    short: "bulma",
    type: "frontend",
    logoPath: "/svg/Bulma.svg",
  },
  {
    iconName: "foundation",
    name: "Foundation",
    short: "foundation",
    type: "frontend",
    logoPath: "/svg/Foundation.svg",
  },
  {
    iconName: "materialize",
    name: "Materialize",
    short: "materialize",
    type: "frontend",
    logoPath: "/svg/Materialize.svg",
  },
  {
    iconName: "postcss",
    name: "PostCSS",
    short: "postcss",
    type: "frontend",
    logoPath: "/svg/PostCSS.svg",
  },
  {
    iconName: "handlebars",
    name: "Handlebars",
    short: "hbs",
    type: "frontend",
    logoPath: "/svg/Handlebars.svg",
  },
  {
    iconName: "vuetify",
    name: "Vuetify",
    short: "vuetify",
    type: "frontend",
    logoPath: "/svg/Veutify.svg",
  },
  {
    iconName: "vuestorefront",
    name: "Vue Storefront",
    short: "vsf",
    type: "frontend",
    logoPath: "/svg/Vue-Storefront.svg",
  },
  {
    iconName: "quasar",
    name: "Quasar",
    short: "quasar",
    type: "frontend",
    logoPath: "/svg/Quasar.svg",
  },
  {
    iconName: "reactbootstrap",
    name: "React Bootstrap",
    short: "reactbootstrap",
    type: "frontend",
    logoPath: "/svg/React-Bootstrap.svg",
  },
  {
    iconName: "qwik",
    name: "Qwik",
    short: "qwik",
    type: "frontend",
    logoPath: "/svg/Qwik.svg",
  },
  {
    iconName: "p5js",
    name: "p5.js",
    short: "p5",
    type: "frontend",
    logoPath: "/svg/p5-JS.svg",
  },
  {
    iconName: "storybook",
    name: "Storybook",
    short: "storybook",
    type: "frontend",
    logoPath: "/svg/Storybook.svg",
  },

  // 🔧 Backend
  {
    iconName: "nodejs",
    name: "Node.js",
    short: "node",
    type: "backend",
    logoPath: "/svg/Node.js.svg",
  },
  {
    iconName: "graphql",
    name: "GraphQL",
    short: "gql",
    type: "backend",
    logoPath: "/svg/GraphQL.svg",
  },
  {
    iconName: "socketio",
    name: "Socket.IO",
    short: "socket",
    type: "backend",
    logoPath: "/svg/Socket.io.svg",
  },
  {
    iconName: "deno",
    name: "Deno",
    short: "deno",
    type: "backend",
    logoPath: "/svg/Deno.svg",
  },
  {
    iconName: "bun",
    name: "Bun",
    short: "bun",
    type: "backend",
    logoPath: "/svg/Bun.svg",
  },
  {
    iconName: "apache",
    name: "Apache",
    short: "apache",
    type: "backend",
    logoPath: "/svg/Apache.svg",
  },
  {
    iconName: "tomcat",
    name: "Apache Tomcat",
    short: "tomcat",
    type: "backend",
    logoPath: "/svg/Apache-Tomcat.svg",
  },
  {
    iconName: "rabbitmq",
    name: "RabbitMQ",
    short: "rabbitmq",
    type: "backend",
    logoPath: "/svg/RabbitMQ.svg",
  },
  {
    iconName: "kafka",
    name: "Apache Kafka",
    short: "kafka",
    type: "backend",
    logoPath: "/svg/Apache-Kafka.svg",
  },
  {
    iconName: "algolia",
    name: "Algolia",
    short: "algolia",
    type: "backend",
    logoPath: "/svg/Algolia.svg",
  },
  {
    iconName: "envoy",
    name: "Envoy",
    short: "envoy",
    type: "backend",
    logoPath: "/svg/Envoy.svg",
  },
  {
    iconName: "jaeger",
    name: "Jaeger Tracing",
    short: "jaeger",
    type: "backend",
    logoPath: "/svg/Jaeger-Tracing.svg",
  },
  {
    iconName: "opentelemetry",
    name: "OpenTelemetry",
    short: "otel",
    type: "backend",
    logoPath: "/svg/OpenTelemetry.svg",
  },

  // 🧪 Testing
  {
    iconName: "jest",
    name: "Jest",
    short: "jest",
    type: "testing",
    logoPath: "/svg/Jest.svg",
  },
  {
    iconName: "vitejs",
    name: "Vite.js",
    short: "vitejs",
    type: "frontend",
    logoPath: "/svg/Vitejs.svg",
  },
  {
    iconName: "cypress",
    name: "Cypress",
    short: "cypress",
    type: "testing",
    logoPath: "/svg/Cypress.svg",
  },
  {
    iconName: "playwright",
    name: "Playwright",
    short: "pw",
    type: "testing",
    logoPath: "/svg/Playwrite.svg",
  },
  {
    iconName: "selenium",
    name: "Selenium",
    short: "selenium",
    type: "testing",
    logoPath: "/svg/Selenium.svg",
  },
  {
    iconName: "pytest",
    name: "Pytest",
    short: "pytest",
    type: "testing",
    logoPath: "/svg/pytest.svg",
  },
  {
    iconName: "jasmine",
    name: "Jasmine",
    short: "jasmine",
    type: "testing",
    logoPath: "/svg/Jasmine.svg",
  },
  {
    iconName: "mocha",
    name: "Mocha",
    short: "mocha",
    type: "testing",
    logoPath: "/svg/Mocha.svg",
  },
  {
    iconName: "karma",
    name: "Karma",
    short: "karma",
    type: "testing",
    logoPath: "/svg/Karma.svg",
  },
  {
    iconName: "protractor",
    name: "Protractor",
    short: "protractor",
    type: "testing",
    logoPath: "/svg/Protractor-Test.svg",
  },
  {
    iconName: "cucumber",
    name: "Cucumber",
    short: "cucumber",
    type: "testing",
    logoPath: "/svg/Cucumber.svg",
  },
  {
    iconName: "gatling",
    name: "Gatling",
    short: "gatling",
    type: "testing",
    logoPath: "/svg/Gatling.svg",
  },
  {
    iconName: "junit",
    name: "JUnit",
    short: "junit",
    type: "testing",
    logoPath: "/svg/JUnit.svg",
  },
  {
    iconName: "rspec",
    name: "RSpec",
    short: "rspec",
    type: "testing",
    logoPath: "/svg/RSpec.svg",
  },
  {
    iconName: "karate",
    name: "Karate Labs",
    short: "karate",
    type: "testing",
    logoPath: "/svg/Karate-Labs.svg",
  },

  // 🗄️ Database
  {
    iconName: "postgresql",
    name: "PostgreSQL",
    short: "pg",
    type: "database",
    logoPath: "/svg/PostgresSQL.svg",
  },
  {
    iconName: "mongodb",
    name: "MongoDB",
    short: "mongo",
    type: "database",
    logoPath: "/svg/MongoDB.svg",
  },
  {
    iconName: "mysql",
    name: "MySQL",
    short: "mysql",
    type: "database",
    logoPath: "/svg/MySQL.svg",
  },
  {
    iconName: "redis",
    name: "Redis",
    short: "redis",
    type: "database",
    logoPath: "/svg/Redis.svg",
  },
  {
    iconName: "sqlite",
    name: "SQLite",
    short: "sqlite",
    type: "database",
    logoPath: "/svg/SQLite.svg",
  },
  {
    iconName: "cassandra",
    name: "Apache Cassandra",
    short: "cassandra",
    type: "database",
    logoPath: "/svg/Apache-Cassandra.svg",
  },
  {
    iconName: "elasticsearch",
    name: "Elasticsearch",
    short: "elastic",
    type: "database",
    logoPath: "/svg/Elastic-Search.svg",
  },
  {
    iconName: "couchdb",
    name: "CouchDB",
    short: "couch",
    type: "database",
    logoPath: "/svg/CouchDB.svg",
  },
  {
    iconName: "mssql",
    name: "Microsoft SQL Server",
    short: "mssql",
    type: "database",
    logoPath: "/svg/Microsoft-SQL-Server.svg",
  },
  {
    iconName: "oracle",
    name: "Oracle",
    short: "oracle",
    type: "database",
    logoPath: "/svg/Oracle.svg",
  },
  {
    iconName: "neo4j",
    name: "Neo4j",
    short: "neo4j",
    type: "database",
    logoPath: "/svg/New4j.svg",
  },
  {
    iconName: "influxdb",
    name: "InfluxDB",
    short: "influx",
    type: "database",
    logoPath: "/svg/InfluxDB.svg",
  },
  {
    iconName: "cosmosdb",
    name: "Cosmos DB",
    short: "cosmos",
    type: "database",
    logoPath: "/svg/Cosmos-BD.svg",
  },
  {
    iconName: "rocksdb",
    name: "RocksDB",
    short: "rocks",
    type: "database",
    logoPath: "/svg/RocksDB.svg",
  },
  {
    iconName: "realm",
    name: "Realm",
    short: "realm",
    type: "database",
    logoPath: "/svg/Realm.svg",
  },
  {
    iconName: "azuresql",
    name: "Azure SQL Database",
    short: "azuresql",
    type: "database",
    logoPath: "/svg/Azure-SQL-Database.svg",
  },
  {
    iconName: "mongoose",
    name: "Mongoose.js",
    short: "mongoose",
    type: "database",
    logoPath: "/svg/Mongoose.js.svg",
  },
  {
    iconName: "sequelize",
    name: "Sequelize",
    short: "sequelize",
    type: "database",
    logoPath: "/svg/Sequelize.svg",
  },
  {
    iconName: "knexjs",
    name: "Knex.js",
    short: "knex",
    type: "database",
    logoPath: "/svg/Knex.js.svg",
  },
  {
    iconName: "sqlalchemy",
    name: "SQLAlchemy",
    short: "sqlalchemy",
    type: "database",
    logoPath: "/svg/SQLAlchemy.svg",
  },
  {
    iconName: "hibernate",
    name: "Hibernate",
    short: "hibernate",
    type: "database",
    logoPath: "/svg/Hibernate.svg",
  },
  {
    iconName: "nhibernate",
    name: "NHibernate",
    short: "nhibernate",
    type: "database",
    logoPath: "/svg/NHibernate.svg",
  },
  {
    iconName: "doctrine",
    name: "Doctrine",
    short: "doctrine",
    type: "database",
    logoPath: "/svg/Doctrine.svg",
  },
  {
    iconName: "liquibase",
    name: "Liquibase",
    short: "liquibase",
    type: "database",
    logoPath: "/svg/Liquibase.svg",
  },

  // 🌐 BAAS
  {
    iconName: "firebase",
    name: "Firebase",
    short: "firebase",
    type: "BAAS",
    logoPath: "/svg/Firebase.svg",
  },
  {
    iconName: "appwrite",
    name: "Appwrite",
    short: "appwrite",
    type: "BAAS",
    logoPath: "/svg/Appwrite.svg",
  },
  {
    iconName: "fauna",
    name: "Fauna",
    short: "fauna",
    type: "BAAS",
    logoPath: "/svg/Fauna.svg",
  },
  {
    iconName: "sanity",
    name: "Sanity",
    short: "sanity",
    type: "BAAS",
    logoPath: "/svg/Sanity.svg",
  },

  // 🎨 Design
  {
    iconName: "figma",
    name: "Figma",
    short: "figma",
    type: "design",
    logoPath: "/svg/Figma.svg",
  },
  {
    iconName: "adobexd",
    name: "Adobe XD",
    short: "xd",
    type: "design",
    logoPath: "/svg/Adobe-XD.svg",
  },
  {
    iconName: "canva",
    name: "Canva",
    short: "canva",
    type: "design",
    logoPath: "/svg/Canva.svg",
  },
  {
    iconName: "photoshop",
    name: "Adobe Photoshop",
    short: "ps",
    type: "design",
    logoPath: "/svg/Adobe-Photoshop.svg",
  },
  {
    iconName: "illustrator",
    name: "Adobe Illustrator",
    short: "ai",
    type: "design",
    logoPath: "/svg/Adobe-Illustrator.svg",
  },
  {
    iconName: "aftereffects",
    name: "After Effects",
    short: "ae",
    type: "design",
    logoPath: "/svg/After-Effects.svg",
  },
  {
    iconName: "premierepro",
    name: "Adobe Premiere Pro",
    short: "pr",
    type: "design",
    logoPath: "/svg/Adobe-Premiere-Pro.svg",
  },
  {
    iconName: "sketch",
    name: "Sketch",
    short: "sketch",
    type: "design",
    logoPath: "/svg/Sketch.svg",
  },
  {
    iconName: "blender",
    name: "Blender",
    short: "blender",
    type: "design",
    logoPath: "/svg/Blender.svg",
  },
  {
    iconName: "gimp",
    name: "GIMP",
    short: "gimp",
    type: "design",
    logoPath: "/svg/GIMP.svg",
  },
  {
    iconName: "inkscape",
    name: "Inkscape",
    short: "inkscape",
    type: "design",
    logoPath: "/svg/Inkscape-.svg",
  },
  {
    iconName: "maya",
    name: "Autodesk Maya",
    short: "maya",
    type: "design",
    logoPath: "/svg/Autodesk-Maya.svg",
  },

  // 🤖 AI / ML
  {
    iconName: "tensorflow",
    name: "TensorFlow",
    short: "tensorflow",
    type: "ai",
    logoPath: "/svg/TensorFlow.svg",
  },
  {
    iconName: "pytorch",
    name: "PyTorch",
    short: "torch",
    type: "ai",
    logoPath: "/svg/PyTorch.svg",
  },
  {
    iconName: "openai",
    name: "OpenAI",
    short: "openai",
    type: "ai",
    logoPath: "/svg/OpenAPI.svg",
  },
  {
    iconName: "keras",
    name: "Keras",
    short: "keras",
    type: "ai",
    logoPath: "/svg/Keras.svg",
  },
  {
    iconName: "numpy",
    name: "NumPy",
    short: "numpy",
    type: "ai",
    logoPath: "/svg/NumPy.svg",
  },
  {
    iconName: "pandas",
    name: "Pandas",
    short: "pandas",
    type: "ai",
    logoPath: "/svg/Pandas.svg",
  },
  {
    iconName: "jupyter",
    name: "Jupyter",
    short: "jupyter",
    type: "ai",
    logoPath: "/svg/Jupyter.svg",
  },
  {
    iconName: "matplotlib",
    name: "Matplotlib",
    short: "matplotlib",
    type: "ai",
    logoPath: "/svg/Matplotlib.svg",
  },
  {
    iconName: "streamlit",
    name: "Streamlit",
    short: "streamlit",
    type: "ai",
    logoPath: "/svg/Streamlit.svg",
  },
  {
    iconName: "kaggle",
    name: "Kaggle",
    short: "kaggle",
    type: "ai",
    logoPath: "/svg/Kaggle.svg",
  },
  {
    iconName: "opencv",
    name: "OpenCV",
    short: "opencv",
    type: "ai",
    logoPath: "/svg/OpenCV.svg",
  },
  {
    iconName: "anaconda",
    name: "Anaconda",
    short: "anaconda",
    type: "ai",
    logoPath: "/svg/Anaconda.svg",
  },

  // 🛠️ DevOps
  {
    iconName: "docker",
    name: "Docker",
    short: "docker",
    type: "devops",
    logoPath: "/svg/Docker.svg",
  },
  {
    iconName: "kubernetes",
    name: "Kubernetes",
    short: "k8s",
    type: "devops",
    logoPath: "/svg/Kubernetes.svg",
  },
  {
    iconName: "nginx",
    name: "NGINX",
    short: "nginx",
    type: "devops",
    logoPath: "/svg/NGINX.svg",
  },
  {
    iconName: "githubactions",
    name: "GitHub Actions",
    short: "gha",
    type: "devops",
    logoPath: "/svg/GitHub-Actions.svg",
  },
  {
    iconName: "aws",
    name: "AWS",
    short: "aws",
    type: "devops",
    logoPath: "/svg/AWS.svg",
  },
  {
    iconName: "gcp",
    name: "Google Cloud",
    short: "gcp",
    type: "devops",
    logoPath: "/svg/Google-Cloud.svg",
  },
  {
    iconName: "azure",
    name: "Azure",
    short: "azure",
    type: "devops",
    logoPath: "/svg/Azure.svg",
  },
  {
    iconName: "jenkins",
    name: "Jenkins",
    short: "jenkins",
    type: "devops",
    logoPath: "/svg/Jenkins.svg",
  },
  {
    iconName: "gitlab",
    name: "GitLab",
    short: "gitlab",
    type: "devops",
    logoPath: "/svg/GitLab.svg",
  },
  {
    iconName: "circleci",
    name: "CircleCI",
    short: "circle",
    type: "devops",
    logoPath: "/svg/CircleCI.svg",
  },
  {
    iconName: "terraform",
    name: "Terraform",
    short: "tf",
    type: "devops",
    logoPath: "/svg/HashiCorp-Terraform.svg",
  },
  {
    iconName: "ansible",
    name: "Ansible",
    short: "ansible",
    type: "devops",
    logoPath: "/svg/Ansible.svg",
  },
  {
    iconName: "prometheus",
    name: "Prometheus",
    short: "prometheus",
    type: "devops",
    logoPath: "/svg/Prometheus.svg",
  },
  {
    iconName: "grafana",
    name: "Grafana",
    short: "grafana",
    type: "devops",
    logoPath: "/svg/Grafana.svg",
  },
  {
    iconName: "vercel",
    name: "Vercel",
    short: "vercel",
    type: "devops",
    logoPath: "/svg/Vercel.svg",
  },
  {
    iconName: "heroku",
    name: "Heroku",
    short: "heroku",
    type: "devops",
    logoPath: "/svg/Heroku.svg",
  },
  {
    iconName: "digitalocean",
    name: "Digital Ocean",
    short: "do",
    type: "devops",
    logoPath: "/svg/Digital-Ocean.svg",
  },
  {
    iconName: "vagrant",
    name: "Vagrant",
    short: "vagrant",
    type: "devops",
    logoPath: "/svg/HashiCorp-Vagrant.svg",
  },
  {
    iconName: "vault",
    name: "Vault",
    short: "vault",
    type: "devops",
    logoPath: "/svg/HashiCorp-Vault.svg",
  },
  {
    iconName: "consul",
    name: "Consul",
    short: "consul",
    type: "devops",
    logoPath: "/svg/Consul.svg",
  },
  {
    iconName: "travisci",
    name: "Travis CI",
    short: "travis",
    type: "devops",
    logoPath: "/svg/Travis-CI.svg",
  },
  {
    iconName: "bamboo",
    name: "Bamboo",
    short: "bamboo",
    type: "devops",
    logoPath: "/svg/Bamboo.svg",
  },
  {
    iconName: "argocd",
    name: "Argo CD",
    short: "argocd",
    type: "devops",
    logoPath: "/svg/Argo-CD.svg",
  },
  {
    iconName: "helm",
    name: "Helm",
    short: "helm",
    type: "devops",
    logoPath: "/svg/Helm.svg",
  },
  {
    iconName: "rancher",
    name: "Rancher",
    short: "rancher",
    type: "devops",
    logoPath: "/svg/Rancher.svg",
  },
  {
    iconName: "k3s",
    name: "K3s",
    short: "k3s",
    type: "devops",
    logoPath: "/svg/K3s.svg",
  },
  {
    iconName: "podman",
    name: "Podman",
    short: "podman",
    type: "devops",
    logoPath: "/svg/Podman.svg",
  },
  {
    iconName: "portainer",
    name: "Portainer",
    short: "portainer",
    type: "devops",
    logoPath: "/svg/Portainer.svg",
  },
  {
    iconName: "cloudflare",
    name: "Cloudflare",
    short: "cloudflare",
    type: "devops",
    logoPath: "/svg/Cloudflare.svg",
  },
  {
    iconName: "cloudflareworkers",
    name: "Cloudflare Workers",
    short: "cfworkers",
    type: "devops",
    logoPath: "/svg/Cloudflare-Workers.svg",
  },
  {
    iconName: "traefik",
    name: "Traefik Proxy",
    short: "traefik",
    type: "devops",
    logoPath: "/svg/Traefik-Proxy.svg",
  },
  {
    iconName: "packer",
    name: "Packer",
    short: "packer",
    type: "devops",
    logoPath: "/svg/Packer.svg",
  },
  {
    iconName: "openstack",
    name: "OpenStack",
    short: "openstack",
    type: "devops",
    logoPath: "/svg/OpenStack.svg",
  },
  {
    iconName: "kibana",
    name: "Kibana",
    short: "kibana",
    type: "devops",
    logoPath: "/svg/Kibana.svg",
  },
  {
    iconName: "logstash",
    name: "Logstash",
    short: "logstash",
    type: "devops",
    logoPath: "/svg/Logstash.svg",
  },
  {
    iconName: "elasticbeats",
    name: "Elastic Beats",
    short: "beats",
    type: "devops",
    logoPath: "/svg/Elastic-Beats.svg",
  },
  {
    iconName: "splunk",
    name: "Splunk",
    short: "splunk",
    type: "devops",
    logoPath: "/svg/Splunk.svg",
  },
  {
    iconName: "sonarqube",
    name: "SonarQube",
    short: "sonar",
    type: "devops",
    logoPath: "/svg/SonarQube.svg",
  },
  {
    iconName: "azuredevops",
    name: "Azure DevOps",
    short: "azuredevops",
    type: "devops",
    logoPath: "/svg/Azure-Devops.svg",
  },

  // 🛠️ Tools
  {
    iconName: "git",
    name: "Git",
    short: "git",
    type: "tools",
    logoPath: "/svg/Git.svg",
  },
  {
    iconName: "github",
    name: "GitHub",
    short: "github",
    type: "tools",
    logoPath: "/svg/GitHub.svg",
  },
  {
    iconName: "vscode",
    name: "VS Code",
    short: "vscode",
    type: "tools",
    logoPath: "/svg/Visual-Studio-Code-(VS-Code).svg",
  },
  {
    iconName: "visualstudio",
    name: "Visual Studio",
    short: "vs",
    type: "tools",
    logoPath: "/svg/Visual-Studio.svg",
  },
  {
    iconName: "intellij",
    name: "IntelliJ IDEA",
    short: "intellij",
    type: "tools",
    logoPath: "/svg/IntelliJ-IDEA.svg",
  },
  {
    iconName: "webstorm",
    name: "WebStorm",
    short: "webstorm",
    type: "tools",
    logoPath: "/svg/WebStorm.svg",
  },
  {
    iconName: "pycharm",
    name: "PyCharm",
    short: "pycharm",
    type: "tools",
    logoPath: "/svg/PyCharm.svg",
  },
  {
    iconName: "phpstorm",
    name: "PhpStorm",
    short: "phpstorm",
    type: "tools",
    logoPath: "/svg/PhpStorm.svg",
  },
  {
    iconName: "clion",
    name: "CLion",
    short: "clion",
    type: "tools",
    logoPath: "/svg/CLion.svg",
  },
  {
    iconName: "rider",
    name: "Rider",
    short: "rider",
    type: "tools",
    logoPath: "/svg/Rider.svg",
  },
  {
    iconName: "goland",
    name: "GoLand",
    short: "goland",
    type: "tools",
    logoPath: "/svg/GoLand.svg",
  },
  {
    iconName: "rubymine",
    name: "RubyMine",
    short: "rubymine",
    type: "tools",
    logoPath: "/svg/RubyMine.svg",
  },
  {
    iconName: "datagrip",
    name: "DataGrip",
    short: "datagrip",
    type: "tools",
    logoPath: "/svg/DataGrip.svg",
  },
  {
    iconName: "dataspell",
    name: "DataSpell",
    short: "dataspell",
    type: "tools",
    logoPath: "/svg/DataSpell.svg",
  },
  {
    iconName: "jetbrains",
    name: "JetBrains",
    short: "jetbrains",
    type: "tools",
    logoPath: "/svg/JetBrains.svg",
  },
  {
    iconName: "vim",
    name: "Vim",
    short: "vim",
    type: "tools",
    logoPath: "/svg/Vim.svg",
  },
  {
    iconName: "emacs",
    name: "GNU Emacs",
    short: "emacs",
    type: "tools",
    logoPath: "/svg/GNU-Emacs.svg",
  },
  {
    iconName: "nano",
    name: "Nano",
    short: "nano",
    type: "tools",
    logoPath: "/svg/Nano.svg",
  },
  {
    iconName: "atom",
    name: "Atom",
    short: "atom",
    type: "tools",
    logoPath: "/svg/Atom.svg",
  },
  {
    iconName: "eclipse",
    name: "Eclipse IDE",
    short: "eclipse",
    type: "tools",
    logoPath: "/svg/Eclipse-IDE.svg",
  },
  {
    iconName: "androidstudio",
    name: "Android Studio",
    short: "androidstudio",
    type: "tools",
    logoPath: "/svg/Android-Studio.svg",
  },
  {
    iconName: "xcode",
    name: "Xcode",
    short: "xcode",
    type: "tools",
    logoPath: "/svg/Xcode.svg",
  },
  {
    iconName: "postman",
    name: "Postman",
    short: "postman",
    type: "tools",
    logoPath: "/svg/Postman.svg",
  },
  {
    iconName: "insomnia",
    name: "Insomnia",
    short: "insomnia",
    type: "tools",
    logoPath: "/svg/Insomnia.svg",
  },
  {
    iconName: "webpack",
    name: "Webpack",
    short: "webpack",
    type: "tools",
    logoPath: "/svg/Webpack.svg",
  },
  {
    iconName: "vite",
    name: "Vite",
    short: "vite",
    type: "tools",
    logoPath: "/svg/Vite.svg",
  },
  {
    iconName: "rollup",
    name: "Rollup.js",
    short: "rollup",
    type: "tools",
    logoPath: "/svg/Rollup.js.svg",
  },
  {
    iconName: "babel",
    name: "Babel",
    short: "babel",
    type: "tools",
    logoPath: "/svg/Babel.svg",
  },
  {
    iconName: "eslint",
    name: "ESLint",
    short: "eslint",
    type: "tools",
    logoPath: "/svg/ESLint.svg",
  },
  {
    iconName: "npm",
    name: "NPM",
    short: "npm",
    type: "tools",
    logoPath: "/svg/NPM.svg",
  },
  {
    iconName: "yarn",
    name: "Yarn",
    short: "yarn",
    type: "tools",
    logoPath: "/svg/Yarn.svg",
  },
  {
    iconName: "maven",
    name: "Apache Maven",
    short: "maven",
    type: "tools",
    logoPath: "/svg/Apache-Maven.svg",
  },
  {
    iconName: "gradle",
    name: "Gradle",
    short: "gradle",
    type: "tools",
    logoPath: "/svg/Gradle.svg",
  },
  {
    iconName: "cmake",
    name: "CMake",
    short: "cmake",
    type: "tools",
    logoPath: "/svg/CMake.svg",
  },
  {
    iconName: "composer",
    name: "Composer",
    short: "composer",
    type: "tools",
    logoPath: "/svg/Composer.svg",
  },
  {
    iconName: "nuget",
    name: "NuGet",
    short: "nuget",
    type: "tools",
    logoPath: "/svg/NuGet.svg",
  },
  {
    iconName: "bower",
    name: "Bower",
    short: "bower",
    type: "tools",
    logoPath: "/svg/Bower.svg",
  },
  {
    iconName: "grunt",
    name: "Grunt.js",
    short: "grunt",
    type: "tools",
    logoPath: "/svg/Grunt.js.svg",
  },
  {
    iconName: "gulp",
    name: "Gulp.js",
    short: "gulp",
    type: "tools",
    logoPath: "/svg/Gulp.js.svg",
  },
  {
    iconName: "homebrew",
    name: "Homebrew",
    short: "brew",
    type: "tools",
    logoPath: "/svg/Homebrew.svg",
  },
  {
    iconName: "linux",
    name: "Linux",
    short: "linux",
    type: "tools",
    logoPath: "/svg/Linux.svg",
  },
  {
    iconName: "ubuntu",
    name: "Ubuntu",
    short: "ubuntu",
    type: "tools",
    logoPath: "/svg/Ubuntu.svg",
  },
  {
    iconName: "debian",
    name: "Debian",
    short: "debian",
    type: "tools",
    logoPath: "/svg/Debian.svg",
  },
  {
    iconName: "fedora",
    name: "Fedora",
    short: "fedora",
    type: "tools",
    logoPath: "/svg/Fedora.svg",
  },
  {
    iconName: "centos",
    name: "CentOS",
    short: "centos",
    type: "tools",
    logoPath: "/svg/CentOS.svg",
  },
  {
    iconName: "archlinux",
    name: "Arch Linux",
    short: "arch",
    type: "i use arch btw",
    logoPath: "/svg/Arch-Linux.svg",
  },
  {
    iconName: "gentoo",
    name: "Gentoo",
    short: "gentoo",
    type: "tools",
    logoPath: "/svg/Gentoo.svg",
  },
  {
    iconName: "nixos",
    name: "NixOS",
    short: "nixos",
    type: "tools",
    logoPath: "/svg/NixOS.svg",
  },
  {
    iconName: "redhat",
    name: "Red Hat",
    short: "rhel",
    type: "tools",
    logoPath: "/svg/Red-Hat.svg",
  },
  {
    iconName: "bitbucket",
    name: "BitBucket",
    short: "bitbucket",
    type: "tools",
    logoPath: "/svg/BitBucket.svg",
  },
  {
    iconName: "subversion",
    name: "Apache Subversion",
    short: "svn",
    type: "tools",
    logoPath: "/svg/Apache-Subversion.svg",
  },
  {
    iconName: "tortoisegit",
    name: "TortoiseGit",
    short: "tortoisegit",
    type: "tools",
    logoPath: "/svg/TortoiseGit.svg",
  },
  {
    iconName: "sourcetree",
    name: "Sourcetree",
    short: "sourcetree",
    type: "tools",
    logoPath: "/svg/Sourcetree.svg",
  },
  {
    iconName: "tower",
    name: "Tower",
    short: "tower",
    type: "tools",
    logoPath: "/svg/Tower.svg",
  },
  {
    iconName: "gitbook",
    name: "GitBook",
    short: "gitbook",
    type: "tools",
    logoPath: "/svg/GitBook.svg",
  },
  {
    iconName: "gitpod",
    name: "Gitpod",
    short: "gitpod",
    type: "tools",
    logoPath: "/svg/Gitpod.svg",
  },
  {
    iconName: "codespaces",
    name: "GitHub Codespaces",
    short: "codespaces",
    type: "tools",
    logoPath: "/svg/GitHub-Codespaces.svg",
  },
  {
    iconName: "swagger",
    name: "Swagger",
    short: "swagger",
    type: "tools",
    logoPath: "/svg/Swagger.svg",
  },
  {
    iconName: "openapi",
    name: "OpenAPI",
    short: "openapi",
    type: "tools",
    logoPath: "/svg/OpenAPI.svg",
  },
  {
    iconName: "jira",
    name: "Jira",
    short: "jira",
    type: "tools",
    logoPath: "/svg/Jira.svg",
  },
  {
    iconName: "confluence",
    name: "Confluence",
    short: "confluence",
    type: "tools",
    logoPath: "/svg/Confluence.svg",
  },
  {
    iconName: "trello",
    name: "Trello",
    short: "trello",
    type: "tools",
    logoPath: "/svg/Trello.svg",
  },
  {
    iconName: "slack",
    name: "Slack",
    short: "slack",
    type: "tools",
    logoPath: "/svg/Slack.svg",
  },
  {
    iconName: "gitter",
    name: "Gitter",
    short: "gitter",
    type: "tools",
    logoPath: "/svg/Gitter.svg",
  },
  {
    iconName: "discord",
    name: "Discord.js",
    short: "discordjs",
    type: "tools",
    logoPath: "/svg/Discord.js.svg",
  },
  {
    iconName: "filezilla",
    name: "FileZilla",
    short: "filezilla",
    type: "tools",
    logoPath: "/svg/FileZilla.svg",
  },
  {
    iconName: "putty",
    name: "PuTTY",
    short: "putty",
    type: "tools",
    logoPath: "/svg/PuTTY.svg",
  },
  {
    iconName: "dbeaver",
    name: "DBeaver",
    short: "dbeaver",
    type: "tools",
    logoPath: "/svg/DBeaver.svg",
  },
  {
    iconName: "sqldeveloper",
    name: "SQL Developer",
    short: "sqldeveloper",
    type: "tools",
    logoPath: "/svg/SQL-Developer.svg",
  },
  {
    iconName: "rstudio",
    name: "RStudio",
    short: "rstudio",
    type: "tools",
    logoPath: "/svg/RStudio.svg",
  },
  {
    iconName: "qodana",
    name: "Qodana",
    short: "qodana",
    type: "tools",
    logoPath: "/svg/Qodana.svg",
  },

  // 📱 Mobile
  {
    iconName: "flutter",
    name: "Flutter",
    short: "flutter",
    type: "mobile",
    logoPath: "/svg/Flutter.svg",
  },
  {
    iconName: "reactnative",
    name: "React Native",
    short: "rn",
    type: "mobile",
    logoPath: "/svg/React.svg",
  },
  {
    iconName: "android",
    name: "Android",
    short: "android",
    type: "mobile",
    logoPath: "/svg/Android.svg",
  },
  {
    iconName: "ionic",
    name: "Ionic",
    short: "ionic",
    type: "mobile",
    logoPath: "/svg/Ionic.svg",
  },
  {
    iconName: "capacitor",
    name: "Capacitor",
    short: "capacitor",
    type: "mobile",
    logoPath: "/svg/Capacitor.svg",
  },
  {
    iconName: "cordova",
    name: "Apache Cordova",
    short: "cordova",
    type: "mobile",
    logoPath: "/svg/Apache.svg",
  },
  {
    iconName: "xamarin",
    name: "Xamarin",
    short: "xamarin",
    type: "mobile",
    logoPath: "/svg/Xamarin.svg",
  },
  {
    iconName: "nwjs",
    name: "NW.js",
    short: "nwjs",
    type: "mobile",
    logoPath: "/svg/NW.js-(node-webkit).svg",
  },
  {
    iconName: "electron",
    name: "Electron",
    short: "electron",
    type: "mobile",
    logoPath: "/svg/Electron.svg",
  },
  {
    iconName: "tauri",
    name: "Tauri",
    short: "tauri",
    type: "mobile",
    logoPath: "/svg/Tauri.svg",
  },

  // 🎮 Game Dev
  {
    iconName: "unity",
    name: "Unity",
    short: "unity",
    type: "gamedev",
    logoPath: "/svg/Unity.svg",
  },
  {
    iconName: "unreal",
    name: "Unreal Engine",
    short: "unreal",
    type: "gamedev",
    logoPath: "/svg/Unreal-Engine.svg",
  },
  {
    iconName: "godot",
    name: "Godot Engine",
    short: "godot",
    type: "gamedev",
    logoPath: "/svg/Godot-Engine.svg",
  },

  // 🌐 CMS
  {
    iconName: "wordpress",
    name: "WordPress",
    short: "wp",
    type: "cms",
    logoPath: "/svg/WordPress.svg",
  },
  {
    iconName: "drupal",
    name: "Drupal",
    short: "drupal",
    type: "cms",
    logoPath: "/svg/Drupal.svg",
  },
  {
    iconName: "joomla",
    name: "Joomla",
    short: "joomla",
    type: "cms",
    logoPath: "/svg/WordPress.svg",
  },
  {
    iconName: "ghost",
    name: "Ghost",
    short: "ghost",
    type: "cms",
    logoPath: "/svg/Ghost.svg",
  },
  {
    iconName: "contentful",
    name: "Contentful",
    short: "contentful",
    type: "cms",
    logoPath: "/svg/GraphQL.svg",
  },
  {
    iconName: "strapi",
    name: "Strapi",
    short: "strapi",
    type: "cms",
    logoPath: "/svg/Node.js.svg",
  },
  {
    iconName: "jekyll",
    name: "Jekyll",
    short: "jekyll",
    type: "cms",
    logoPath: "/svg/Jekyll.svg",
  },
  {
    iconName: "hugo",
    name: "Hugo",
    short: "hugo",
    type: "cms",
    logoPath: "/svg/Hugo.svg",
  },
  {
    iconName: "eleventy",
    name: "Eleventy (11ty)",
    short: "11ty",
    type: "cms",
    logoPath: "/svg/Eleventy-(11ty).svg",
  },
  {
    iconName: "webflow",
    name: "Webflow",
    short: "webflow",
    type: "cms",
    logoPath: "/svg/Webflow.svg",
  },
  {
    iconName: "typo3",
    name: "TYPO3",
    short: "typo3",
    type: "cms",
    logoPath: "/svg/TYPO3.svg",
  },
  {
    iconName: "contao",
    name: "Contao",
    short: "contao",
    type: "cms",
    logoPath: "/svg/Contao.svg",
  },
  {
    iconName: "modx",
    name: "MODX",
    short: "modx",
    type: "cms",
    logoPath: "/svg/MODX.svg",
  },
  {
    iconName: "moodle",
    name: "Moodle",
    short: "moodle",
    type: "cms",
    logoPath: "/svg/Moodle.svg",
  },

  // 🛒 E-commerce
  {
    iconName: "woocommerce",
    name: "WooCommerce",
    short: "woo",
    type: "ecommerce",
    logoPath: "/svg/WooCommerce.svg",
  },
  {
    iconName: "shopware",
    name: "Shopware",
    short: "shopware",
    type: "ecommerce",
    logoPath: "/svg/Shopware.svg",
  },
  {
    iconName: "magento",
    name: "Adobe Commerce (Magento)",
    short: "magento",
    type: "ecommerce",
    logoPath: "/svg/Adobe-Commerce-(Magneto).svg",
  },

  // 🔧 Build Tools & Bundlers
  {
    iconName: "turbopack",
    name: "Turbopack",
    short: "turbopack",
    type: "build",
    logoPath: "/svg/Webpack.svg",
  },

  // 🔐 Security & Auth
  {
    iconName: "okta",
    name: "Okta",
    short: "okta",
    type: "security",
    logoPath: "/svg/Okta.svg",
  },

  // 📊 Data & Analytics
  {
    iconName: "hadoop",
    name: "Apache Hadoop",
    short: "hadoop",
    type: "data",
    logoPath: "/svg/Apache-Hadoop.svg",
  },
  {
    iconName: "spark",
    name: "Apache Spark",
    short: "spark",
    type: "data",
    logoPath: "/svg/Apache-Spark.svg",
  },
  {
    iconName: "airflow",
    name: "Apache Airflow",
    short: "airflow",
    type: "data",
    logoPath: "/svg/Apache-Airflow.svg",
  },
  {
    iconName: "networkx",
    name: "NetworkX",
    short: "networkx",
    type: "data",
    logoPath: "/svg/NetworkX.svg",
  },

  // 📚 Other Technologies
  {
    iconName: "markdown",
    name: "Markdown",
    short: "md",
    type: "other",
    logoPath: "/svg/Markdown.svg",
  },
  {
    iconName: "json",
    name: "JSON",
    short: "json",
    type: "other",
    logoPath: "/svg/JSON.svg",
  },
  {
    iconName: "xml",
    name: "XML",
    short: "xml",
    type: "other",
    logoPath: "/svg/XML.svg",
  },
  {
    iconName: "yaml",
    name: "YAML",
    short: "yaml",
    type: "other",
    logoPath: "/svg/YAML.svg",
  },
  {
    iconName: "latex",
    name: "LaTeX",
    short: "latex",
    type: "other",
    logoPath: "/svg/LaTeX.svg",
  },
  {
    iconName: "tex",
    name: "TeX",
    short: "tex",
    type: "other",
    logoPath: "/svg/TeX.svg",
  },
  {
    iconName: "opengl",
    name: "OpenGL",
    short: "opengl",
    type: "other",
    logoPath: "/svg/OpenGL.svg",
  },
  {
    iconName: "opencl",
    name: "OpenCL",
    short: "opencl",
    type: "other",
    logoPath: "/svg/OpenCL.svg",
  },
  {
    iconName: "openal",
    name: "OpenAL",
    short: "openal",
    type: "other",
    logoPath: "/svg/OpenAL.svg",
  },
  {
    iconName: "webassembly",
    name: "WebAssembly",
    short: "wasm",
    type: "other",
    logoPath: "/svg/WebAssembly.svg",
  },
  {
    iconName: "llvm",
    name: "LLVM",
    short: "llvm",
    type: "other",
    logoPath: "/svg/LLVM.svg",
  },
  {
    iconName: "gcc",
    name: "GCC",
    short: "gcc",
    type: "other",
    logoPath: "/svg/GCC.svg",
  },
  {
    iconName: "v8",
    name: "V8",
    short: "v8",
    type: "other",
    logoPath: "/svg/V8.svg",
  },
  {
    iconName: "sdl",
    name: "Simple DirectMedia Layer (SDL)",
    short: "sdl",
    type: "other",
    logoPath: "/svg/Simple-DirectMedia-Layer-(SDL).svg",
  },
  {
    iconName: "ros",
    name: "Robot Operating System (ROS)",
    short: "ros",
    type: "other",
    logoPath: "/svg/Robot-Operating-System-(ROS).svg",
  },
  {
    iconName: "gazebo",
    name: "Gazebo",
    short: "gazebo",
    type: "other",
    logoPath: "/svg/Gazebo.svg",
  },
  {
    iconName: "livewire",
    name: "Livewire",
    short: "livewire",
    type: "other",
    logoPath: "/svg/Livewire.svg",
  },
  {
    iconName: "hardhat",
    name: "Hardhat",
    short: "hardhat",
    type: "other",
    logoPath: "/svg/Hardhat.svg",
  },
  {
    iconName: "jamstack",
    name: "Jamstack",
    short: "jamstack",
    type: "other",
    logoPath: "/svg/Jamstack.svg",
  },
  {
    iconName: "pyscript",
    name: "PyScript",
    short: "pyscript",
    type: "other",
    logoPath: "/svg/PyScript.svg",
  },
  {
    iconName: "processing",
    name: "Processing",
    short: "processing",
    type: "other",
    logoPath: "/svg/Processing.svg",
  },
  {
    iconName: "arduino",
    name: "Arduino",
    short: "arduino",
    type: "other",
    logoPath: "/svg/Arduino.svg",
  },
  {
    iconName: "raspberrypi",
    name: "Raspberry Pi",
    short: "raspi",
    type: "other",
    logoPath: "/svg/Raspberry-Pi.svg",
  },
  {
    iconName: "labview",
    name: "LabVIEW",
    short: "labview",
    type: "other",
    logoPath: "/svg/LabVIEW.svg",
  },
  {
    iconName: "ssh",
    name: "SSH",
    short: "ssh",
    type: "other",
    logoPath: "/svg/SSH.svg",
  },
  {
    iconName: "corejs",
    name: "Core.js",
    short: "corejs",
    type: "other",
    logoPath: "/svg/Core-js.svg",
  },
  {
    iconName: "nodemon",
    name: "Nodemon",
    short: "nodemon",
    type: "other",
    logoPath: "/svg/Nodemon.svg",
  },
  {
    iconName: "uwsgi",
    name: "uWSGI",
    short: "uwsgi",
    type: "other",
    logoPath: "/svg/uWSGI.svg",
  },
  {
    iconName: "codecov",
    name: "Codecov",
    short: "codecov",
    type: "other",
    logoPath: "/svg/Codecov.svg",
  },
  {
    iconName: "browserstack",
    name: "BrowserStack",
    short: "browserstack",
    type: "other",
    logoPath: "/svg/BrowserStack.svg",
  },
  {
    iconName: "salesforce",
    name: "Salesforce",
    short: "salesforce",
    type: "other",
    logoPath: "/svg/Salesforce.svg",
  },
  {
    iconName: "weblate",
    name: "Weblate",
    short: "weblate",
    type: "other",
    logoPath: "/svg/Weblate.svg",
  },
  {
    iconName: "reach",
    name: "Reach",
    short: "reach",
    type: "other",
    logoPath: "/svg/Reach.svg",
  },
  {
    iconName: "nimble",
    name: "Nimble",
    short: "nimble",
    type: "other",
    logoPath: "/svg/Nimble.svg",
  },
  {
    iconName: "poetry",
    name: "Python Poetry",
    short: "poetry",
    type: "other",
    logoPath: "/svg/Python-Poetry.svg",
  },
];
